version: "3"
services:
  rabbitmq:
    image: "rabbitmq:management"
    hostname: "mqtt.example.com"
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_USE_LONGNAME: 'true'
    logging:
      options:
        max-file: "3"
        max-size: "50m"
    volumes:
      - "./etc/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      - "./etc/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
      - "./etc/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie"
      - "./var/lib/rabbitmq:/var/lib/rabbitmq"
      - "/opt/apps/certbot/tls/private.pem:/tls/private.pem"
      - "/opt/apps/certbot/tls/fullchain.pem:/tls/fullchain.pem"
    ports:
      - "1883:1883"
      - "8883:8883"
      - "15676:15676"
      # - "15675:15675"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      # - "15672:15672"
      # - "5672:5672"
      # - "35197:35197"
      # - "15673:15673"
      # - "15674:15674"
      # - "61613:61613"
      # Clustering:
      - "4369:4369"
      - "25672:25672"
